apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-addons
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cluster-addons
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps/helm
    repoURL: https://github.com/joudaon/argocd.git
    targetRevision: HEAD