apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: argocd-image-updater
spec:
  project: default
  source:
    repoURL: https://github.com/joudaon/argocd.git
    targetRevision: HEAD
    path: real_case/helm/applications/in-cluster/argocd-image-updater
    helm:
      valueFiles:
        - values.yaml
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  ignoreDifferences:
    - group: "*"
      kind: "*"