### https://awstip.com/multiple-cluster-bootstrapping-using-argocd-applicationset-edf5d4be9667
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: in-cluster-applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/joudaon/argocd.git
        revision: HEAD
        directories:
        - path: "real_case/helm/applications/in-cluster/*"
  template:
    metadata:
      name: "{{path.basename}}"
      labels:
        app_type: systemApp
    spec:
      project: default
      source:
        repoURL: https://github.com/joudaon/argocd.git
        targetRevision: HEAD
        path: "real_case/helm/applications/in-cluster/{{path.basename}}"
        helm:
          releaseName: "{{path.basename}}"
      destination:
        name: in-cluster
        namespace: '{{ path.basename }}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true