# Default values for nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app_name: nginx
app_version: latest
cpu_limits: 200m
cpu_requests: 100m
environment: dev
memory_limits: 256
memory_requests: 56
node_port: 30002
replicas: 1
animals:
  animal1: dog
  animal2: cat
  animal3: snake
  animal4: turtle