apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp1-namespace-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: root_app
spec:
  project: default
  source:
    repoURL: https://github.com/joudaon/argocd.git
    targetRevision: HEAD
    path: "02_approach_3/helm_manifests/namespace"
    helm:
      releaseName: "myapp1-namespace-dev"
      valueFiles:
        - ../apps/myapp1-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: root-app
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

