apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: myapps
spec:
  project: default
  source:
    repoURL: https://github.com/joudaon/argocd.git
    targetRevision: HEAD
    path: 02_approach_3/argocd/apps/myapps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  #   namespace: myapps
  syncPolicy:
    automated: {}
