apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: myapp1
spec:
  project: default
  source:
    repoURL: https://github.com/joudaon/argocd.git
    targetRevision: HEAD
    path: 02_approach_3/argocd/apps/myapp1
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
