apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: myapps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/joudaon/argocd.git
        revision: HEAD
        files:
        - path: "02_approach_1/helm/custom_apps/apps/**"
  template:
    metadata:
      name: '{{path[4]}}-{{path.basename}}'
      labels:
        environment: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/joudaon/argocd.git
        targetRevision: HEAD
        path: "helm_manifests/custom_apps/base_deployment"
        helm:
          releaseName: "{{path[4]}}"
          valueFiles:
            - ../apps/{{path[4]}}/{{path.basename}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path[4]}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true