apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapps-namespace-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: myapps
spec:
  project: default
  source:
    repoURL: https://github.com/joudaon/argocd.git
    targetRevision: HEAD
    path: "02_approach_3/helm_manifests/namespace"
    helm:
      releaseName: "myapps-namespace-dev"
      valueFiles:
        - ../apps-values/myapps/namespace.yaml
  destination:
    server: https://kubernetes.default.svc
  #   namespace: myapp1
  # syncPolicy:
  #   syncOptions:
  #   - CreateNamespace=true

