apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: nginx
spec:
  project: default
  source:
    repoURL: https://github.com/joudaon/argocd.git
    targetRevision: HEAD
    path: "real_case/helm/applications/base_application"
    helm:
      releaseName: "nginx-dev"
      valueFiles:
        - ../../values/nginx/dev-values.yaml
  destination:
    name: in-cluster
    namespace: nginx
  info:
    - name: Application url
      value: https://dev.example.com
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels: 
        mytestlabel: mytestlabel
