apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
    argocd-image-updater.argoproj.io/image-alias.allow-tags: httpd:latest
  #   argocd-image-updater.argoproj.io/image-alias.force-update: 'true'
  #   argocd-image-updater.argoproj.io/image-alias.pull-secret: 'pullsecret:develop-namespace/develop-app-gitlab-secrets'
  #   argocd-image-updater.argoproj.io/image-alias.update-strategy: latest
  #   argocd-image-updater.argoproj.io/image-list: httpd
  #   argocd-image-updater.argoproj.io/write-back-method: git
  labels:
    name: nginx
spec:
  project: default
  source:
    repoURL: https://github.com/joudaon/argocd.git
    targetRevision: HEAD
    path: "real_case/helm/applications/base_application"
    helm:
      releaseName: "nginx-dev"
      valueFiles:
        - ../../values/nginx/dev-values.yaml
  destination:
    name: dev-cluster
    namespace: nginx
  info:
    - name: Application url
      value: https://dev.example.com
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels: 
        mytestlabel: mytestlabel
