apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-pre
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: nginx-dev
spec:
  project: default
  source:
    repoURL: https://github.com/joudaon/argocd.git
    targetRevision: HEAD
    path: "real_case/helm/applications/base_application"
    helm:
      releaseName: "nginx-pre"
      valueFiles:
        - ../../values/nginx/pre-values.yaml
  destination:
    server: pre-cluster
    namespace: nginx
  info:
    - name: Application url
      value: https://pre.example.com
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
