apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root_app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: root_app
spec:
  project: default
  source:
    repoURL: https://github.com/joudaon/argocd.git
    targetRevision: HEAD
    path: 02_approach_2
    directory:
      recurse: true
