apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-pre
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # argocd.argoproj.io/manifest-generate-paths: .
    # argocd-image-updater.argoproj.io/image-alias.allow-tags: 'regexp:^1.3.0-SNAPSHOT.[0-9]+$'
    # argocd-image-updater.argoproj.io/image-alias.force-update: 'true'
    # argocd-image-updater.argoproj.io/image-alias.pull-secret: 'pullsecret:develop-namespace/develop-app-gitlab-secrets'
    # argocd-image-updater.argoproj.io/image-alias.update-strategy: latest
    # argocd-image-updater.argoproj.io/image-list: httpd:latest
    # argocd-image-updater.argoproj.io/write-back-method: git
  labels:
    name: nginx
spec:
  project: default
  source:
    repoURL: https://github.com/joudaon/argocd.git
    targetRevision: HEAD
    path: "real_case/helm/applications/base_application"
    helm:
      releaseName: nginx
      valueFiles:
        - ../../values/nginx/pre-values.yaml
  destination:
    name: pre-cluster
    namespace: nginx
  info:
    - name: Application url
      value: https://pre.example.com
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    managedNamespaceMetadata:
      labels: 
        mytestlabel: mytestlabel