# Slave Cluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: slave
nodes:
  - role: control-plane
    labels:
      kubernetes.io/os: linux
      ingress-ready: "true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8081  # HTTP for slave
      - containerPort: 443
        hostPort: 8444  # HTTPS for slave
