apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: minio
      targetRevision: 13.6.2
      helm:
        valueFiles:
          - $values/kube-prometheus-stack/02-argocd/minio/values.yaml
    - repoURL: https://github.com/joudaon/argocd.git
      targetRevision: HEAD
      ref: values
  destination:
    name: kind-slave
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
  info:
    - name: Artifact Hub
      value: https://artifacthub.io/packages/helm/bitnami/minio