auth:
  rootUser: admin
  rootPassword: admin

defaultBuckets: "my-bucket"

mode: standalone

persistence:
  enabled: true
  size: 5Gi

service:
  type: ClusterIP

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10

ingress:
  enabled: true
  hostname: minio.myorg.com
  ingressClassName: nginx
  path: /
  pathType: Prefix
