apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 25.10.0
      helm:
        valueFiles:
          - $values/kube-prometheus-stack/02-argocd/prometheus/values.yaml
    - repoURL: https://github.com/joudaon/argocd.git
      targetRevision: HEAD
      ref: values
  destination:
    name: kind-slave
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
  info:
    - name: Artifact Hub
      value: https://artifacthub.io/packages/helm/prometheus-community/prometheus
