alertmanager:
  enabled: true

kubeStateMetrics:
  enabled: false

nodeExporter:
  enabled: false

pushgateway:
  enabled: false

server:
  enabled: true
  persistentVolume:
    enabled: true
    size: 10Gi
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: nginx