apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: prometheus
      targetRevision: 9.2.9
      helm:
        valueFiles:
          - $values/kube-prometheus-stack/02-argocd/grafana/values.yaml
    - repoURL: https://github.com/joudaon/argocd.git
      targetRevision: HEAD
      ref: values
  destination:
    name: in-cluster
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
    - ServerSideApply=true
  info:
    - name: Artifact Hub
      value: https://artifacthub.io/packages/helm/grafana/grafana
