# Master Cluster
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: master
nodes:
  - role: control-plane
    labels:
      kubernetes.io/os: linux
      ingress-ready: "true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 8080  # HTTP for master
      - containerPort: 443
        hostPort: 8443  # HTTPS for master
