apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: prevent-critical-namespace-deletion
  annotations:
    policies.kyverno.io/title: Prevent Critical Namespace Deletion
    policies.kyverno.io/category: Security
    kyverno.io/kyverno-version: 1.10.0
    policies.kyverno.io/minversion: 1.10.0
    kyverno.io/kubernetes-version: "1.26"
    policies.kyverno.io/subject: "Namespace"
    policies.kyverno.io/description: >-
      This policy prevents the deletion of critical Kubernetes namespaces such as 'default',
      'kube-system', and 'kube-public' to ensure cluster stability and security.

spec:
  validationFailureAction: Enforce
  background: false
  rules:
  - name: block-critical-namespace-deletion
    match:
      any:
      - resources:
          kinds:
          - Namespace
          names:
          - "default"
          - "kube-system"
          - "kube-public"
    validate:
      message: "Deletion of critical namespaces is not allowed."
      deny: {}