apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: loadbalancer-external
---
apiVersion: v1
kind: Namespace
metadata:
  name: loadbalancer-internal