apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: css-fake
spec:
  provider:
    fake:
      data:
      - key: "myapp1-dev-var1"
        value: "hello from myapp1-dev-var1"
        version: "v1"
      - key: "myapp1-dev-var2"
        value: "hello from myapp1-dev-var2"
        version: "v1"
      - key: "myapp1-pre-var1"
        value: "hello from myapp1-pre-var1"
        version: "v1"
