apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: css-fake
spec:
  provider:
    fake:
      data:
      - key: "nginx-dev-var1"
        value: "GOODBYE SECRET from nginx-dev-var1"
        version: "v1"
      - key: "nginx-dev-var2"
        value: "hello from nginx-dev-var2"
        version: "v1"
      - key: "nginx-pre-var1"
        value: "hello from nginx-pre-var1"
        version: "v1"
      - key: "/nginx/dev/var3"
        value: "hello from nginx-dev-var3"
        version: "v1"
