apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    environment: {{ .Values.environment }}
    owner: 'myself'
  annotations:
    link.argocd.argoproj.io/external-link: http://mycustomurl.com
    configmap.reloader.stakater.com/reload: cm-{{ .Release.Name }}
    secret.reloader.stakater.com/reload: secret-{{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        owner: 'myself'
      annotations:
        # checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        # rollme: {{ randAlphaNum 15 | quote }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: httpd:{{ .Values.app_version }} # <-- {{ .Release.Name }} IMAGE
        securityContext:
          allowPrivilegeEscalation: false
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "echo $MY_NODE_NAME - $HOSTNAME > htdocs/index.html"]
        # LIFECYCLE DEFINITION END
        ports:
        - containerPort: 80
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        {{- if .Values.database_enabled }}
        - name: DATABASE
          value: "Hello database"
        {{- end }}
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
          - configMapRef:
              name: cm-{{ .Release.Name }}
          - secretRef:
              name: secret-{{ .Values.app_name}}
        resources:
          limits:
            cpu: {{ .Values.cpu_limits }}
            memory: {{ .Values.memory_limits }}Mi
          requests:
            cpu: {{ .Values.cpu_requests }}
            memory: {{ .Values.memory_requests }}Mi
