apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: es-{{ .Values.app_name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: css-fake
    kind: ClusterSecretStore
  target:
    name: s-{{ .Values.app_name }}
  dataFrom:
  - find:
      key:
        regexp: "{{ .Values.app_name }}"
  data:
  - secretKey: {{ .Values.app_name }}-{{ .Values.environment }}-var1
    remoteRef:
      key: {{ .Values.app_name }}-{{ .Values.environment }}-var1
      version: v1