apiVersion: external-secrets.io/v1beta1 
kind: ExternalSecret
metadata:
  name: es-{{ .Release.Name }}
spec:
  refreshInterval: 2m
  secretStoreRef:
    name: css-fake-{{ .Release.Name }}
    kind: ClusterSecretStore
  target:
    name: secret-{{ .Release.Name }}
#   dataFrom:
#   - find:
#       name:
#         regexp: {{ .Release.Name }}
  data:
  - secretKey: {{ .Release.Name }}_{{ .Values.environment }}_var1
    remoteRef:
      key: {{ .Release.Name }}-{{ .Values.environment }}-var1
      version: v1