apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}
  name: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_name }}
    environment: {{ .Values.environment }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.app_name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ .Values.node_port }}